class AddColumnsToItem < ActiveRecord::Migration
  def change
    add_column :items, :income_issues_wages, :string
    add_column :items, :income_issues_interest_dividends_schedule_b, :string
    add_column :items, :income_issues_business_income_schedule_c, :string
    add_column :items, :income_issues_capital_gain_loss_schedule_d, :string
    add_column :items, :income_issues_ira_pension, :string
    add_column :items, :income_issues_social_security_benefits, :string
    add_column :items, :income_issues_alimony, :string
    add_column :items, :income_issues_rental_royalty_partnership_s_corp_schedule_e, :string
    add_column :items, :income_issues_farming_income_schedule_f, :string
    add_column :items, :income_issues_unemployment, :string
    add_column :items, :income_issues_gambling_winnings, :string
    add_column :items, :income_issues_cancellation_of_debt, :string
    add_column :items, :income_issues_settlement_proceeds, :string
    add_column :items, :income_issues_other_income_issues, :string
    add_column :items, :deduction_issues_alimony, :string
    add_column :items, :deduction_issues_education_expenses_including_student_loan_interest, :string
    add_column :items, :deduction_issues_moving_expenses, :string
    add_column :items, :deduction_issues_ira_deduction, :string
    add_column :items, :deduction_issues_medical_and_dental_expenses, :string
    add_column :items, :deduction_issues_state_and_local_taxes, :string
    add_column :items, :deduction_issues_home_mortgage_interest, :string
    add_column :items, :deduction_issues_other_interest_expenses, :string
    add_column :items, :deduction_issues_charitable_contributions, :string
    add_column :items, :deduction_issues_casualty_and_theft_losses, :string
    add_column :items, :deduction_issues_unreimbursed_employee_business_expenses, :string
    add_column :items, :deduction_issues_other_itemized_deductions, :string
    add_column :items, :deduction_issues_business_expenses_schedule_c, :string
    add_column :items, :credit_issues_child_and_dependent_care_credit, :string
    add_column :items, :credit_issues_education_credits, :string
    add_column :items, :credit_issues_child_tax_credit_additional_child_tax_credit, :string
    add_column :items, :credit_issues_earned_income_tax_credit, :string
    add_column :items, :credit_issues_first_time_homebuyer_credit, :string
    add_column :items, :credit_issues_premium_tax_credit, :string
    add_column :items, :credit_issues_other_credits, :string
    add_column :items, :status_issues_ssn_tin, :string
    add_column :items, :status_issues_itin, :string
    add_column :items, :status_issues_filing_status, :string
    add_column :items, :status_issues_personal_dependency_exemptions, :string
    add_column :items, :status_issues_refund_related_identity_theft, :string
    add_column :items, :status_issues_nonfiler, :string
    add_column :items, :status_issues_worker_classification, :string
    add_column :items, :tax_issues_self_employment_tax, :string
    add_column :items, :tax_issues_suspected_return_preparer_fraud, :string
    add_column :items, :tax_issues_estimated_tax_payments, :string
    add_column :items, :tax_issues_withholdings, :string
    add_column :items, :tax_issues_refund, :string
    add_column :items, :tax_issues_assessment_statute_of_limitations, :string
    add_column :items, :tax_issues_collection_statute_of_limitations, :string
    add_column :items, :tax_issues_refund_statute_of_limitations, :string
    add_column :items, :penalty_issues_trust_fund_recovery_penalty, :string
    add_column :items, :penalty_issues_other_civil_penalties, :string
    add_column :items, :penalty_issues_additional_tax_on_distributions_from_qualified_retirement_plans, :string
    add_column :items, :penalty_issues_individual_shared_responsibility_payment, :string
    add_column :items, :collection_issues_payments, :string
    add_column :items, :collection_issues_installment_payment_agreement_ipa, :string
    add_column :items, :collection_issues_offer_in_compromise_oic, :string
    add_column :items, :collection_issues_currently_not_collectible_cnc, :string
    add_column :items, :collection_issues_liens, :string
    add_column :items, :collection_issues_levies_including_federal_payment_levy_program, :string
  end
end
