# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20171110205326) do

  create_table "items", force: :cascade do |t|
    t.string   "client_ssn"
    t.string   "client_name"
    t.string   "case_type"
    t.string   "status"
    t.datetime "date_opened"
    t.datetime "date_closed"
    t.datetime "created_at",                                       null: false
    t.datetime "updated_at",                                       null: false
    t.string   "case_id"
    t.string   "income_issues_wages"
    t.string   "income_issues_interest_dividends_schedule_b"
    t.string   "income_issues_business_income_schedule_c"
    t.string   "income_issues_capital_gain_loss_schedule_d"
    t.string   "income_issues_ira_pension"
    t.string   "income_issues_social_security_benefits"
    t.string   "income_issues_alimony"
    t.string   "income_issues_rental_royalty_partnership_s_corp"
    t.string   "income_issues_farming_income_schedule_f"
    t.string   "income_issues_unemployment"
    t.string   "income_issues_gambling_winnings"
    t.string   "income_issues_cancellation_of_debt"
    t.string   "income_issues_settlement_proceeds"
    t.string   "income_issues_other_income_issues"
    t.string   "deduction_issues_alimony"
    t.string   "deduction_issues_education_expenses_including_st"
    t.string   "deduction_issues_moving_expenses"
    t.string   "deduction_issues_ira_deduction"
    t.string   "deduction_issues_medical_and_dental_expenses"
    t.string   "deduction_issues_state_and_local_taxes"
    t.string   "deduction_issues_home_mortgage_interest"
    t.string   "deduction_issues_other_interest_expenses"
    t.string   "deduction_issues_charitable_contributions"
    t.string   "deduction_issues_casualty_and_theft_losses"
    t.string   "deduction_issues_unreimbursed_employee_business"
    t.string   "deduction_issues_other_itemized_deductions"
    t.string   "deduction_issues_business_expenses_schedule_c"
    t.string   "credit_issues_child_and_dependent_care_credit"
    t.string   "credit_issues_education_credits"
    t.string   "credit_issues_child_tax_credit_additional_child"
    t.string   "credit_issues_earned_income_tax_credit"
    t.string   "credit_issues_first_time_homebuyer_credit"
    t.string   "credit_issues_premium_tax_credit"
    t.string   "credit_issues_other_credits"
    t.string   "status_issues_ssn_tin"
    t.string   "status_issues_itin"
    t.string   "status_issues_filing_status"
    t.string   "status_issues_personal_dependency_exemptions"
    t.string   "status_issues_injured_spouse"
    t.string   "status_issues_innocent_spouse"
    t.string   "status_issues_employment_related_identity_theft"
    t.string   "status_issues_refund_related_identity_theft"
    t.string   "status_issues_nonfiler"
    t.string   "status_issues_worker_classification"
    t.string   "tax_issues_self_employment_tax"
    t.string   "tax_issues_suspected_return_preparer_fraud"
    t.string   "tax_issues_estimated_tax_payments"
    t.string   "tax_issues_withholdings"
    t.string   "tax_issues_refund"
    t.string   "tax_issues_assessment_statute_of_limitations"
    t.string   "tax_issues_collection_statute_of_limitations"
    t.string   "tax_issues_refund_statute_of_limitations"
    t.string   "penalty_issues_trust_fund_recovery_penalty"
    t.string   "penalty_issues_other_civil_penalties"
    t.string   "penalty_issues_additional_tax_on_distributions_f"
    t.string   "penalty_issues_individual_shared_responsibility"
    t.string   "collection_issues_payments"
    t.string   "collection_issues_installment_payment_agreement"
    t.string   "collection_issues_offer_in_compromise_oic"
    t.string   "collection_issues_currently_not_collectible_cnc"
    t.string   "collection_issues_liens"
    t.string   "collection_issues_levies_including_federal_payme"
    t.string   "inventory_beginning_case_inventory"
    t.string   "inventory_new_cases_opened_during_the_reporting"
    t.string   "inventory_total_number_of_cases_worked_during_th"
    t.string   "inventory_cases_closed_during_the_reporting_peri"
    t.string   "inventory_ending_case_inventory"
    t.string   "accounts_return_processing"
    t.string   "accounts_penalty_abatement"
    t.string   "accounts_injured_spouse"
    t.string   "accounts_backup_withholding"
    t.string   "exams_correspondence_exam"
    t.string   "exams_office_or_field_exam"
    t.string   "exams_automated_underreporter"
    t.string   "exams_automated_substitute_for_return"
    t.string   "exams_audit_reconsideration"
    t.string   "collection_automated_collection_system"
    t.string   "collection_field_collection"
    t.string   "collection_offer_in_compromise"
    t.string   "collection_lien_unit"
    t.string   "collection_bankruptcy"
    t.string   "appeals_exam_appeals"
    t.string   "appeals_collection_due_process"
    t.string   "appeals_collection_appeals_process"
    t.string   "appeals_oic_appeals"
    t.string   "appeals_penalty_abatement_appeals"
    t.string   "appeals_other_appeals"
    t.string   "litigation_us_tax_court"
    t.string   "litigation_other_federal_courts"
    t.string   "miscellaneous_identity_protection_specialized_un"
    t.string   "miscellaneous_innocent_spouse_unit"
    t.string   "miscellaneous_ss_8_unit"
    t.string   "miscellaneous_itin_unit"
    t.string   "miscellaneous_trust_fund_recovery_penalty"
    t.string   "total"
    t.string   "additional_the_amount_in_controversy_exceeds_500"
    t.string   "additional_the_taxpayers_income_exceeds_250_of"
    t.string   "additional_matters_worked_in_more_than_on_irs_fu"
    t.string   "additional_more_than_one_tax_year"
    t.string   "additional_representation_of_esl_taxpayers"
    t.string   "additional_joint_representation_of_taxpayers"
    t.string   "additional_representation_by_volunteers"
    t.string   "additional_state_tax_matters"
    t.string   "tax_court_does_the_clinic_participate_in_the_us"
    t.string   "tax_court_list_the_places_of_trial_location_serv"
    t.string   "tax_court_appearances"
    t.string   "tax_court_no_appearances"
    t.string   "tax_court_number_of_informal_consultations_in_th"
    t.string   "closed_case_a_number_of_cases_in_which_the_taxpa"
    t.string   "closed_case_b_number_of_cases_in_which_the_taxpa"
    t.string   "closed_case_c_total_amount_of_dollars_refunded_i"
    t.string   "closed_case_d_total_decrease_in_corrected_tax_li"
    t.string   "name_of_clinic"
    t.string   "grant_year"
    t.string   "income_issues_1_wages"
    t.string   "income_issues_2_interest_divid"
    t.string   "income_issues_3_business_incom"
    t.string   "income_issues_4_capital_gain_o"
    t.string   "income_issues_5_ira_pension"
    t.string   "income_issues_6_social_securit"
    t.string   "income_issues_7_alimony"
    t.string   "income_issues_8_rental_royalty"
    t.string   "income_issues_9_farming_income"
    t.string   "income_issues_10_unemployment"
    t.string   "income_issues_11_gambling_winn"
    t.string   "income_issues_12_cancellation"
    t.string   "income_issues_13_settlement_pr"
    t.string   "income_issues_14_other"
    t.string   "deduction_issues_15_alimony"
    t.string   "deduction_issues_16_education"
    t.string   "deduction_issues_17_moving_exp"
    t.string   "deduction_issues_18_ira_deduct"
    t.string   "deduction_issues_19_medical_an"
    t.string   "deduction_issues_20_state_and"
    t.string   "deduction_issues_21_home_mortg"
    t.string   "deduction_issues_22_other_inte"
    t.string   "deduction_issues_23_charitable"
    t.string   "deduction_issues_24_casualty_a"
    t.string   "deduction_issues_25_unreimburs"
    t.string   "deduction_issues_26_other_item"
    t.string   "deduction_issues_27_business_e"
    t.string   "credit_issues_28_child_and_dep"
    t.string   "credit_issues_29_education_cre"
    t.string   "credit_issues_30_child_tax_cre"
    t.string   "credit_issues_31_earned_income"
    t.string   "credit_issues_32_first_time_ho"
    t.string   "credit_issues_33_premium_tax_c"
    t.string   "credit_issues_34_other_credits"
    t.string   "status_issues_35_ssn_tin"
    t.string   "status_issues_36_itin"
    t.string   "status_issues_37_filing_status"
    t.string   "status_issues_38_personal_depe"
    t.string   "status_issues_39_injured_spous"
    t.string   "status_issues_40_innocent_spou"
    t.string   "status_issues_41_employment_re"
    t.string   "status_issues_42_refund_relate"
    t.string   "status_issues_43_nonfiler"
    t.string   "status_issues_44_worker_classi"
    t.string   "tax_issues_45_self_employment"
    t.string   "tax_issues_46_suspected_return"
    t.string   "tax_issues_47_estimated_tax_pa"
    t.string   "tax_issues_48_withholdings"
    t.string   "tax_issues_49_refund"
    t.string   "tax_issues_50_assessment_statu"
    t.string   "tax_issues_51_collection_statu"
    t.string   "tax_issues_52_refund_statute_o"
    t.string   "penalty_issues_53_trust_fund_r"
    t.string   "penalty_issues_54_other_civil"
    t.string   "penalty_issues_55_additional_t"
    t.string   "penalty_issues_56_individual_s"
    t.string   "collection_issues_57_payments"
    t.string   "collection_issues_58_installme"
    t.string   "collection_issues_59_offer_in"
    t.string   "collection_issues_60_currently"
    t.string   "collection_issues_61_liens"
    t.string   "collection_issues_62_levies_in"
    t.string   "total_case_issues_worked_add_l"
    t.string   "case_inventory_1a_beginning_ca"
    t.string   "case_inventory_1b_new_cases_op"
    t.string   "case_inventory_1c_total_number"
    t.string   "case_inventory_1d_cases_closed"
    t.string   "case_inventory_1e_ending_case"
    t.string   "accounts_management_2a_return"
    t.string   "accounts_management_2b_penalty"
    t.string   "accounts_management_2c_injured"
    t.string   "accounts_management_2d_backup"
    t.string   "exams_2e_correspondence_exam"
    t.string   "exams_2f_office_or_field_exam"
    t.string   "exams_2g_automated_underreport"
    t.string   "exams_2h_automated_substitute"
    t.string   "exams_2i_audit_reconsideration"
    t.string   "collection_2j_automated_collec"
    t.string   "collection_2k_field_collection"
    t.string   "collection_2l_offer_in_comprom"
    t.string   "collection_2m_lien_unit"
    t.string   "collection_2n_bankruptcy"
    t.string   "appeals_2o_exam_appeals"
    t.string   "appeals_2p_collection_due_proc"
    t.string   "appeals_2q_collection_appeals"
    t.string   "appeals_2r_oic_appeals"
    t.string   "appeals_2s_penalty_abatement_a"
    t.string   "appeals_2t_other_appeals"
    t.string   "litigation_2u_us_tax_court"
    t.string   "litigation_2v_other_federal_co"
    t.string   "miscellaneous_2w_identity_prot"
    t.string   "miscellaneous_2x_innocent_spou"
    t.string   "miscellaneous_2y_ss_8_unit"
    t.string   "miscellaneous_2z_itin_unit"
    t.string   "miscellaneous_2aa_trust_fund_r"
    t.string   "total_add_items_2a_through_2aa"
    t.string   "additional_case_information_3"
    t.string   "additional_case_information_4"
    t.string   "additional_case_information_5"
    t.string   "additional_case_information_6"
    t.string   "additional_case_information_7"
    t.string   "additional_case_information_8"
    t.string   "additional_case_information_9"
    t.string   "additional_case_information_10"
    t.string   "us_tax_court_activities_12_num"
    t.string   "us_tax_court_activities_13_num"
    t.string   "us_tax_court_activities_14_num"
    t.string   "closed_case_outcomes_15a_numbe"
    t.string   "closed_case_outcomes_15b_numbe"
    t.string   "closed_case_outcomes_15c_total"
    t.string   "closed_case_outcomes_15d_total"
  end

  create_table "settings", force: :cascade do |t|
    t.string   "var",                   null: false
    t.text     "value"
    t.integer  "thing_id"
    t.string   "thing_type", limit: 30
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "settings", ["thing_type", "thing_id", "var"], name: "index_settings_on_thing_type_and_thing_id_and_var", unique: true

end
