class AddColumnsToItem < ActiveRecord::Migration
  def change
    add_column :items, :income_issues_1_wages, :string
    add_column :items, :income_issues_2_interest_divid, :string
    add_column :items, :income_issues_3_business_incom, :string
    add_column :items, :income_issues_4_capital_gain_o, :string
    add_column :items, :income_issues_5_ira_pension, :string
    add_column :items, :income_issues_6_social_securit, :string
    add_column :items, :income_issues_7_alimony, :string
    add_column :items, :income_issues_8_rental_royalty, :string
    add_column :items, :income_issues_9_farming_income, :string
    add_column :items, :income_issues_10_unemployment, :string
    add_column :items, :income_issues_11_gambling_winn, :string
    add_column :items, :income_issues_12_cancellation, :string
    add_column :items, :income_issues_13_settlement_pr, :string
    add_column :items, :income_issues_14_other, :string
    add_column :items, :deduction_issues_15_alimony, :string
    add_column :items, :deduction_issues_16_education, :string
    add_column :items, :deduction_issues_17_moving_exp, :string
    add_column :items, :deduction_issues_18_ira_deduct, :string
    add_column :items, :deduction_issues_19_medical_an, :string
    add_column :items, :deduction_issues_20_state_and, :string
    add_column :items, :deduction_issues_21_home_mortg, :string
    add_column :items, :deduction_issues_22_other_inte, :string
    add_column :items, :deduction_issues_23_charitable, :string
    add_column :items, :deduction_issues_24_casualty_a, :string
    add_column :items, :deduction_issues_25_unreimburs, :string
    add_column :items, :deduction_issues_26_other_item, :string
    add_column :items, :deduction_issues_27_business_e, :string
    add_column :items, :credit_issues_28_child_and_dep, :string
    add_column :items, :credit_issues_29_education_cre, :string
    add_column :items, :credit_issues_30_child_tax_cre, :string
    add_column :items, :credit_issues_31_earned_income, :string
    add_column :items, :credit_issues_32_first_time_ho, :string
    add_column :items, :credit_issues_33_premium_tax_c, :string
    add_column :items, :credit_issues_34_other_credits, :string
    add_column :items, :status_issues_35_ssn_tin, :string
    add_column :items, :status_issues_36_itin, :string
    add_column :items, :status_issues_37_filing_status, :string
    add_column :items, :status_issues_38_personal_depe, :string
    add_column :items, :status_issues_39_injured_spous, :string
    add_column :items, :status_issues_40_innocent_spou, :string
    add_column :items, :status_issues_41_employment_re, :string
    add_column :items, :status_issues_42_refund_relate, :string
    add_column :items, :status_issues_43_nonfiler, :string
    add_column :items, :status_issues_44_worker_classi, :string
    add_column :items, :tax_issues_45_self_employment, :string
    add_column :items, :tax_issues_46_suspected_return, :string
    add_column :items, :tax_issues_47_estimated_tax_pa, :string
    add_column :items, :tax_issues_48_withholdings, :string
    add_column :items, :tax_issues_49_refund, :string
    add_column :items, :tax_issues_50_assessment_statu, :string
    add_column :items, :tax_issues_51_collection_statu, :string
    add_column :items, :tax_issues_52_refund_statute_o, :string
    add_column :items, :penalty_issues_53_trust_fund_r, :string
    add_column :items, :penalty_issues_54_other_civil, :string
    add_column :items, :penalty_issues_55_additional_t, :string
    add_column :items, :penalty_issues_56_individual_s, :string
    add_column :items, :collection_issues_57_payments, :string
    add_column :items, :collection_issues_58_installme, :string
    add_column :items, :collection_issues_59_offer_in, :string
    add_column :items, :collection_issues_60_currently, :string
    add_column :items, :collection_issues_61_liens, :string
    add_column :items, :collection_issues_62_levies_in, :string
    add_column :items, :total_case_issues_worked_add_l, :string
    add_column :items, :case_inventory_1a_beginning_ca, :string
    add_column :items, :case_inventory_1b_new_cases_op, :string
    add_column :items, :case_inventory_1c_total_number, :string
    add_column :items, :case_inventory_1d_cases_closed, :string
    add_column :items, :case_inventory_1e_ending_case, :string
    add_column :items, :accounts_management_2a_return, :string
    add_column :items, :accounts_management_2b_penalty, :string
    add_column :items, :accounts_management_2c_injured, :string
    add_column :items, :accounts_management_2d_backup, :string
    add_column :items, :exams_2e_correspondence_exam, :string
    add_column :items, :exams_2f_office_or_field_exam, :string
    add_column :items, :exams_2g_automated_underreport, :string
    add_column :items, :exams_2h_automated_substitute, :string
    add_column :items, :exams_2i_audit_reconsideration, :string
    add_column :items, :collection_2j_automated_collec, :string
    add_column :items, :collection_2k_field_collection, :string
    add_column :items, :collection_2l_offer_in_comprom, :string
    add_column :items, :collection_2m_lien_unit, :string
    add_column :items, :collection_2n_bankruptcy, :string
    add_column :items, :appeals_2o_exam_appeals, :string
    add_column :items, :appeals_2p_collection_due_proc, :string
    add_column :items, :appeals_2q_collection_appeals, :string
    add_column :items, :appeals_2r_oic_appeals, :string
    add_column :items, :appeals_2s_penalty_abatement_a, :string
    add_column :items, :appeals_2t_other_appeals, :string
    add_column :items, :litigation_2u_us_tax_court, :string
    add_column :items, :litigation_2v_other_federal_co, :string
    add_column :items, :miscellaneous_2w_identity_prot, :string
    add_column :items, :miscellaneous_2x_innocent_spou, :string
    add_column :items, :miscellaneous_2y_ss_8_unit, :string
    add_column :items, :miscellaneous_2z_itin_unit, :string
    add_column :items, :miscellaneous_2aa_trust_fund_r, :string
    add_column :items, :total_add_items_2a_through_2aa, :string
    add_column :items, :additional_case_information_3, :string
    add_column :items, :additional_case_information_4, :string
    add_column :items, :additional_case_information_5, :string
    add_column :items, :additional_case_information_6, :string
    add_column :items, :additional_case_information_7, :string
    add_column :items, :additional_case_information_8, :string
    add_column :items, :additional_case_information_9, :string
    add_column :items, :additional_case_information_10, :string
    add_column :items, :us_tax_court_activities_12_num, :string
    add_column :items, :us_tax_court_activities_13_num, :string
    add_column :items, :us_tax_court_activities_14_num, :string
    add_column :items, :closed_case_outcomes_15a_numbe, :string
    add_column :items, :closed_case_outcomes_15b_numbe, :string
    add_column :items, :closed_case_outcomes_15c_total, :string
    add_column :items, :closed_case_outcomes_15d_total, :string
  end
end
